app/chat/[id]/page.tsx, app/chat/page.tsx, app/colors/page.tsx, app/tracker/page.tsx, components/Chat.tsx, package-lock.json, tailwind.config.js
- Creates the initial frontend routing layout.
=> Create frontend routing layout

components/ChatHistoryButton.tsx, components/Sidemenu.tsx, components/SidemenuButton.tsx, package-lock.json, package.json
- Created the sidemenu component
- Separated the buttons into .tsx files
- Tested on my local machine
=> Implement sidemenu on frontend

components/AddCashExpenseModal.tsx, components/Header.tsx
- Created the modal for addig new cash expenses
- Only frontend, not connected to any database, expenses stored in a useState array
- manual testing
=> feat: implemented modal for adding cash expenses

.gitignore, app/chat/[id]/page.tsx, app/chat/page.tsx, app/layout.tsx, components/Chat.tsx, components/Header.tsx, styles/styles.css, types/types.ts
- changed layout
- added structure for chat
- basic functionalities for chat
- manual testing
=> Implement chat screen

.eslintrc.json, app/categories/page.tsx, components/EditCategory.tsx, components/Sidemenu.tsx, components/SidemenuButton.tsx, package-lock.json, package.json, types/types.ts
- the layout of the categories page is done
- mobile layout is not implemented!
- not working with LIVE data
- manual testing
=> Create categories page

app/transactions/page.tsx, components/SidemenuButton.tsx
- feat: implemented transactions page
- feat: added page link to sidemenu
- ...
- ...
=> Implement transaction list page

middleware.ts
=> Add page visit based activiy logging

app/kpi/page.tsx, components/Sidemenu.tsx, components/SidemenuButton.tsx, package-lock.json, package.json
- Now we can see our kpi in a seperate page (UI only)
- Manual test, please check it because sometimes I have a render issue related to nextjs:
issue:
Error: Text content does not match server-rendered HTML.
Warning: Text content did not match. Server: "618" Client: "437"
See more info here: https://nextjs.org/docs/messages/react-hydration-error
=> Add KPI page

app/layout.tsx, components/ContextProvider.tsx, components/Header.tsx, components/ManualExpenseModal.tsx, components/Sidemenu.tsx
- added global context
- fixed width of sidemenu
- implemented sidemenu open - close funtionality
- manual testing
=> Add sidemenu open and close functionality

app/api/kpi/route.ts, app/kpi/page.tsx, middleware.ts, types/types.ts
- feat: updated column_name
- feat: created kpi api
- feat: updated kpi page with fetching
- feat: added IKPI interface
- ...
- ...
=> Connect KPI measurements

middleware.ts
=> Protect routes

app/api/categories/route.ts, app/api/goals/route.ts, app/api/transactions/route.ts, app/kpi/page.tsx, app/transactions/page.tsx, types/types.ts
- feat: added transactions api
- feat: added goals api
- feat: added categories api
- chore: updated types
- feat: updated transactions page
- chore: formatted code
- feat: added loading animation
- ...
- ...
=> Link transactions to the DB

app/api/chat/route.ts, app/api/chatHistory/route.ts, app/api/sidemenu/route.ts, components/Chat.tsx, components/Sidemenu.tsx, components/SidemenuButton.tsx, types/types.ts
- feat: added new chat creation
- feat: added sidemenu calls
- feat: added overflow support
- feat: updated chat fetching
- chore: reverted changes
- feat: added chat history save
- feat: updated chat saving
- chore: ran formatter
- ...
- ...
=> Connect chat functions to the db

components/Header.tsx, components/Sidemenu.tsx, components/SidemenuButton.tsx, middleware.ts
=> Fix API auth errors

app/api/getBalance/route.ts, app/api/transactions/route.ts
=> Update balance amount handling

app/api/kpi/route.ts
=> Update allUsersCount query

app/api/categories/route.ts, app/api/sidemenu/route.ts, app/api/transactions/route.ts, app/categories/page.tsx, app/goals/page.tsx, app/plots/page.tsx, app/transactions/page.tsx, components/AddCashExpenseModal.tsx, types/types.ts
- fix: fixed api issues
- feat: test if record is deletable
- fix: fixed mismatched type
- chore: removed logs
- chore: added promise for fetching
- ...
- ...
=> Quality of life updates for deletion and balance calculation

components/Chat.tsx
=> Add chat response animation

app/api/categories/route.ts, app/api/chat/route.ts, app/api/getBalance/route.ts, app/api/goals/route.ts, app/api/kpi/route.ts, app/api/transactions/route.ts, middleware.ts, utils/registerActivity.ts
=> Refine activity measurement

app/api/chat/route.ts, app/transactions/page.tsx, components/Sidemenu.tsx
=> Add LLM based record creation

app/api/transactions/route.ts
=> Fix transaction deletion

app/plots/page.tsx
=> Fix plot value inversion

app/goals/page.tsx
=> Fix value inversion again
